#!/usr/bin/python

import argparse
import os

from itermocil import itermocil

parser = argparse.ArgumentParser(description='Process a teamocil file in iTerm2 without tmux.')

parser.add_argument("teamocil_layout",
                    help="the teamocil layout you wish to process",
                    metavar="layout_name")

# teamocil compatible flags:

parser.add_argument("--here",
                    help="run in the current terminal",
                    action="store_true",
                    default=False)

parser.add_argument("--edit",
                    help="edit file in $EDITOR",
                    action="store_true",
                    default=False)

parser.add_argument("--show",
                    help="show the layout instead of executing it",
                    action="store_true",
                    default=False)

parser.add_argument("--layout",
                    help="use specified file rather than that in the .teamocil directory",
                    action="store_true",
                    default=None)

# iTermocil flags

parser.add_argument("--showscript",
                    help="show the Applescript built to configure iTerm rather than running it",
                    action="store_true",
                    default=None)

args = parser.parse_args()

# teamocil files live in a hidden directory in the home directory
teamocil_dir = os.path.join(os.path.expanduser("~"), ".teamocil")

# Build teamocil file path basec on presence of --layout flag.
if args.layout:
    filepath = os.path.join(os.getcwd(), args.teamocil_layout)
else:
    filepath = os.path.join(teamocil_dir, args.teamocil_layout + ".yml")

# Check teamocil file exists
if not os.path.isfile(filepath):
    print "ERROR: There is no file at: " + filepath
    exit(1)

# If --show then output and exit()
if args.show:
    with open(filepath, 'r') as fin:
        print fin.read()
        exit(0)

# If --edit the try to launch editor and exit
if args.edit:
    editor = os.getenv('EDITOR')
    if editor:
        os.system('%s %s' % (editor, filepath))
        exit(0)
    else:
        print "ERROR: No editor set in $EDITOR"
        exit(1)

# Parse the teamocil file and execute it.
instance = itermocil(filepath, here=args.here)

if args.showscript:
    print instance.script()
else:
    instance.execute()
